name: Hermes
version: '${pluginVersion}'
main: me.moros.hermes.Hermes
bootstrapper: me.moros.hermes.HermesBootstrap
author: Moros
description: Chat formatting plugin for PaperMC.
website: https://github.com/PrimordialMoros/Hermes
api-version: '1.20'
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
