[versions]
configurate = "4.1.2"
cloud = "1.8.3"
paper = "1.19.4-R0.1-SNAPSHOT"
papi = "2.11.3"
checker = "0.6.27"
shadow = "8.1.1"

[libraries]
configurate-hocon = { module = "org.spongepowered:configurate-hocon", version.ref = "configurate" }
cloud-minecraft = { module = "cloud.commandframework:cloud-minecraft-extras", version.ref = "cloud" }
cloud-paper = { module = "cloud.commandframework:cloud-paper", version.ref = "cloud" }

# Bukkit
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
papi = { module = "me.clip:placeholderapi", version.ref = "papi" }

[plugins]
checker = { id = "org.checkerframework", version.ref = "checker" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
